### ISSUE TITLE
Conda CI Failure Mid February 2022

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1020]
Error:
~~~
2022-02-11T02:12:39.2514067Z [command]/usr/share/miniconda3/condabin/mamba create --name test
2022-02-11T02:12:39.8237286Z ##[warning]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 934, in exception_converter
        raise e
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 882, in _wrapped_main
        result = do_call(args, p)
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 748, in do_call
        exit_code = create(args, parser)
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 624, in create
        return install(args, parser, "create")
      File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 577, in install
        if not transaction.prompt():
    UnboundLocalError: local variable 'transaction' referenced before assignment

`$ /usr/share/miniconda3/condabin/mamba create --name test`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=/usr/share/miniconda3
           CONDA_PKGS_DIR=/home/runner/conda_pkgs_dir
               CONDA_ROOT=/usr/share/miniconda3
           CURL_CA_BUNDLE=<not set>
      DEPLOYMENT_BASEPATH=/opt/runner
        GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
              GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_f573de62-4c7d-4
                          ce0-8c28-fa0c51a3d380
                     PATH=/usr/share/miniconda3/condabin:/home/linuxbrew/.linuxbrew/bin:/home/li
                          nuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/ru
                          nner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.g
                          hcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/loc
                          al/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap
                          /bin
       REQUESTS_CA_BUNDLE=<not set>
        SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
            SSL_CERT_FILE=<not set>
               SWIFT_PATH=/usr/share/swift/usr/bin

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : /usr/share/miniconda3/.condarc
                          /home/runner/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=5.11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/share/miniconda3  (writable)
      conda av data dir : /usr/share/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /usr/share/miniconda3/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.11.0-1028-azure ubuntu/20.04.3 glibc/2.31
                UID:GID : 1001:121
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

2022-02-11T02:12:39.8241789Z 
2022-02-11T02:12:39.8241916Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2022-02-11T02:12:39.8242070Z 
2022-02-11T02:12:39.8242181Z     Traceback (most recent call last):
2022-02-11T02:12:39.8242708Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
2022-02-11T02:12:39.8243034Z         return func(*args, **kwargs)
2022-02-11T02:12:39.8243480Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 934, in exception_converter
2022-02-11T02:12:39.8285960Z         raise e
2022-02-11T02:12:39.8286772Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
2022-02-11T02:12:39.8287203Z         exit_code = _wrapped_main(*args, **kwargs)
2022-02-11T02:12:39.8287682Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 882, in _wrapped_main
2022-02-11T02:12:39.8287990Z         result = do_call(args, p)
2022-02-11T02:12:39.8288423Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 748, in do_call
2022-02-11T02:12:39.8288733Z         exit_code = create(args, parser)
2022-02-11T02:12:39.8289172Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 624, in create
2022-02-11T02:12:39.8289497Z         return install(args, parser, "create")
2022-02-11T02:12:39.8289921Z       File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 577, in install
2022-02-11T02:12:39.8290246Z         if not transaction.prompt():
2022-02-11T02:12:39.8290651Z     UnboundLocalError: local variable 'transaction' referenced before assignment
2022-02-11T02:12:39.8290868Z 
2022-02-11T02:12:39.8291090Z `$ /usr/share/miniconda3/condabin/mamba create --name test`
2022-02-11T02:12:39.8291266Z 
2022-02-11T02:12:39.8291359Z   environment variables:
2022-02-11T02:12:39.8291567Z                  CIO_TEST=<not set>
2022-02-11T02:12:39.8291805Z                     CONDA=/usr/share/miniconda3
2022-02-11T02:12:39.8292054Z            CONDA_PKGS_DIR=/home/runner/conda_pkgs_dir
2022-02-11T02:12:39.8292321Z                CONDA_ROOT=/usr/share/miniconda3
2022-02-11T02:12:39.8292542Z            CURL_CA_BUNDLE=<not set>
2022-02-11T02:12:39.8292777Z       DEPLOYMENT_BASEPATH=/opt/runner
2022-02-11T02:12:39.8293079Z         GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
2022-02-11T02:12:39.8293546Z               GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_f573de62-4c7d-4
2022-02-11T02:12:39.8293923Z                           ce0-8c28-fa0c51a3d380
2022-02-11T02:12:39.8294218Z                      PATH=/usr/share/miniconda3/condabin:/home/linuxbrew/.linuxbrew/bin:/home/li
2022-02-11T02:12:39.8294675Z                           nuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/ru
2022-02-11T02:12:39.8295033Z                           nner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.g
2022-02-11T02:12:39.8295367Z                           hcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/loc
2022-02-11T02:12:39.8295702Z                           al/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap
2022-02-11T02:12:39.8295957Z                           /bin
2022-02-11T02:12:39.8296179Z        REQUESTS_CA_BUNDLE=<not set>
2022-02-11T02:12:39.8296548Z         SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
2022-02-11T02:12:39.8296803Z             SSL_CERT_FILE=<not set>
2022-02-11T02:12:39.8297051Z                SWIFT_PATH=/usr/share/swift/usr/bin
2022-02-11T02:12:39.8297208Z 
2022-02-11T02:12:39.8297293Z      active environment : None
2022-02-11T02:12:39.8297552Z        user config file : /home/runner/.condarc
2022-02-11T02:12:39.8297842Z  populated config files : /usr/share/miniconda3/.condarc
2022-02-11T02:12:39.8298101Z                           /home/runner/.condarc
2022-02-11T02:12:39.8298327Z           conda version : 4.11.0
2022-02-11T02:12:39.8298613Z     conda-build version : not installed
2022-02-11T02:12:39.8298856Z          python version : 3.9.10.final.0
2022-02-11T02:12:39.8299087Z        virtual packages : __linux=5.11.0=0
2022-02-11T02:12:39.8299318Z                           __glibc=2.31=0
2022-02-11T02:12:39.8299529Z                           __unix=0=0
2022-02-11T02:12:39.8299782Z                           __archspec=1=x86_64
2022-02-11T02:12:39.8300048Z        base environment : /usr/share/miniconda3  (writable)
2022-02-11T02:12:39.8300331Z       conda av data dir : /usr/share/miniconda3/etc/conda
2022-02-11T02:12:39.8300587Z   conda av metadata url : None
2022-02-11T02:12:39.8300976Z            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
2022-02-11T02:12:39.8301478Z                           https://conda.anaconda.org/conda-forge/noarch
2022-02-11T02:12:39.8301791Z           package cache : /home/runner/conda_pkgs_dir
2022-02-11T02:12:39.8302058Z        envs directories : /usr/share/miniconda3/envs
2022-02-11T02:12:39.8302320Z                           /home/runner/.conda/envs
2022-02-11T02:12:39.8302599Z                platform : linux-64
2022-02-11T02:12:39.8303059Z              user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.11.0-1028-azure ubuntu/20.04.3 glibc/2.31
2022-02-11T02:12:39.8303363Z                 UID:GID : 1001:121
2022-02-11T02:12:39.8303564Z              netrc file : None
2022-02-11T02:12:39.8303783Z            offline mode : False
2022-02-11T02:12:39.8303919Z 
2022-02-11T02:12:39.8303924Z 
2022-02-11T02:12:39.8304075Z An unexpected error has occurred. Conda has prepared the above report.
2022-02-11T02:12:39.8304822Z ##[warning]

2022-02-11T02:12:39.8305343Z 
2022-02-11T02:12:39.8305348Z 
2022-02-11T02:12:39.8305447Z                   __    __    __    __
2022-02-11T02:12:39.8305663Z                  /  \  /  \  /  \  /  \
2022-02-11T02:12:39.8305857Z                 /    \/    \/    \/    \
2022-02-11T02:12:39.8306315Z ███████████████/  /██/  /██/  /██/  /████████████████████████
2022-02-11T02:12:39.8306546Z               /  / \   / \   / \   / \  \____
2022-02-11T02:12:39.8306770Z              /  /   \_/   \_/   \_/   \    o \__,
2022-02-11T02:12:39.8306975Z             / _/                       \_____/  `
2022-02-11T02:12:39.8307172Z             |/
2022-02-11T02:12:39.8307500Z         ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
2022-02-11T02:12:39.8307853Z         ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
2022-02-11T02:12:39.8308226Z         ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
2022-02-11T02:12:39.8308578Z         ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
2022-02-11T02:12:39.8308933Z         ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
2022-02-11T02:12:39.8309310Z         ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝
2022-02-11T02:12:39.8309555Z 
2022-02-11T02:12:39.8309675Z         mamba (0.21.0) supported by @QuantStack
2022-02-11T02:12:39.8309831Z 
2022-02-11T02:12:39.8310044Z         GitHub:  https://github.com/mamba-org/mamba
2022-02-11T02:12:39.8310331Z         Twitter: https://twitter.com/QuantStack
2022-02-11T02:12:39.8310496Z 
2022-02-11T02:12:39.8310753Z █████████████████████████████████████████████████████████████
2022-02-11T02:12:39.8310908Z 
2022-02-11T02:12:39.8310913Z 
2022-02-11T02:12:39.8310996Z Looking for: []
2022-02-11T02:12:39.8311105Z 
2022-02-11T02:12:39.8807320Z ##[endgroup]
2022-02-11T02:12:39.8807736Z ##[endgroup]
2022-02-11T02:12:39.8810575Z ##[error]The process '/usr/share/miniconda3/condabin/mamba' failed with exit code 1
2022-02-11T02:12:39.9661635Z Post job cleanup.
2022-02-11T02:12:40.0840388Z [command]/usr/bin/git version
2022-02-11T02:12:40.0888697Z git version 2.35.1
2022-02-11T02:12:40.0920449Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-02-11T02:12:40.0957842Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-02-11T02:12:40.1183875Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-02-11T02:12:40.1209541Z http.https://github.com/.extraheader
2022-02-11T02:12:40.1218040Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-02-11T02:12:40.1254563Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
~~~

Seems a mamba regressions.

**Comment by traversaro** [comment]
Probably it was https://github.com/mamba-org/mamba/releases/tag/2022.02.07 that took a few days to propagate to conda-forge due to https://github.com/conda-forge/status/issues/125 .

**Comment by traversaro** [comment]
It was indeed tracked by https://github.com/mamba-org/mamba/pull/1460, a release should appear soon to fix this.

**Comment by Huitongtong** [comment]
> Probably it was https://github.com/mamba-org/mamba/releases/tag/2022.02.07 that took a few days to propagate to conda-forge due to [conda-forge/status#125](https://github.com/conda-forge/status/issues/125) .

Any updates on this issue? I still have the same error for creating 'mamba create -n robotologyenv'  environment.

**Comment by traversaro** [comment]
A new mamba release is arriving soon (see https://github.com/mamba-org/mamba/commit/b3aef48677b08e540e7ec4b08c03d6099ff48969). 

However, the workaround is quite simple, just create the environment with some packages instead of completly empty, such as:
~~~
mamba create -n robotologyenv cmake
~~~

**Comment by traversaro** [comment]
Workaround added in https://github.com/robotology/robotology-superbuild/pull/1026 and removed in https://github.com/robotology/robotology-superbuild/pull/1034 .
