### ISSUE TITLE
conda macos packages generation failure end of February 2022

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1041]
~~~
usr/local/miniconda/envs  
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 123, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve_for_action
    t = self.solve(specs)
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - ace
 - sdl
 - libcxx >=12.0.1
 - libopencv 4.5.5.*
 - sdl2
 - libjpeg-turbo 2.*
 - bash-completion
 - python 3.9.* *_cpython
 - swig
 - tinyxml
 - sqlite 3.*
 - qt 5.12.9.* *_4
 - eigen
 - ycm-cmake-modules
 - robot-testing-framework

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package libopencv-4.5.5-py31h83f2b0d_0 requires harfbuzz >=3.2.0,<4.0a0, but none of the providers can be installed
- 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 2051, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 788, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/metadata.py", line 2120, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/metadata.py", line 781, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 546, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 408, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 373, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 138, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 125, in mamba_get_install_actions
    conflict_packages = parse_problems(str(e))
  File "/usr/local/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 40, in parse_problems
    assert words[1] == "package"
AssertionError
~~~

**Comment by traversaro** [comment]
This is a yarp build problem, so yet another reason to migrate yarp to conda-forge as next step in https://github.com/robotology/robotology-superbuild/issues/752 . However, it is too late to do this in time for 2022.02.0, let's get this to work in someway.

**Comment by traversaro** [comment]
First of all, let's try to see which version are used when building the robsub from source in the CI, as that one seems to be working fine. From https://github.com/robotology/robotology-superbuild/runs/5341743720, this is the used environment:
~~~
2022-02-26T02:17:35.7659880Z # packages in environment at /Users/runner/miniconda3/envs/test:
2022-02-26T02:17:35.7661270Z #
2022-02-26T02:17:35.7661580Z # Name                    Version                   Build  Channel
2022-02-26T02:17:35.7662370Z ace                       7.0.6                he49afe7_0    conda-forge
2022-02-26T02:17:35.7662950Z ampl-mp                   3.1.0             h2beb688_1006    conda-forge
2022-02-26T02:17:35.7663340Z asio                      1.14.1               he49afe7_1    conda-forge
2022-02-26T02:17:35.7663750Z assimp                    5.2.1                h1224e73_0    conda-forge
2022-02-26T02:17:35.7664880Z atk-1.0                   2.36.0               he69c4ee_4    conda-forge
2022-02-26T02:17:35.7665270Z boost                     1.74.0           py39ha1f3e3e_5    conda-forge
2022-02-26T02:17:35.7665700Z boost-cpp                 1.74.0               hff03dee_4    conda-forge
2022-02-26T02:17:35.7666070Z bzip2                     1.0.8                h0d85af4_4    conda-forge
2022-02-26T02:17:35.7666480Z c-ares                    1.18.1               h0d85af4_0    conda-forge
2022-02-26T02:17:35.7666890Z c-compiler                1.4.0                h774085c_0    conda-forge
2022-02-26T02:17:35.7667270Z ca-certificates           2021.10.8            h033912b_0    conda-forge
2022-02-26T02:17:35.7667740Z cairo                     1.16.0            he43a7df_1008    conda-forge
2022-02-26T02:17:35.7668120Z cctools                   973.0.1              hd9211c8_6    conda-forge
2022-02-26T02:17:35.7668520Z cctools_osx-64            973.0.1              h609b070_6    conda-forge
2022-02-26T02:17:35.7668890Z clang                     12.0.1               h694c41f_4    conda-forge
2022-02-26T02:17:35.7669310Z clang-12                  12.0.1          default_he082bbe_4    conda-forge
2022-02-26T02:17:35.7669740Z clang_osx-64              12.0.1               h633439f_6    conda-forge
2022-02-26T02:17:35.7670120Z clangxx                   12.0.1          default_he082bbe_4    conda-forge
2022-02-26T02:17:35.7670540Z clangxx_osx-64            12.0.1               hdb584c0_6    conda-forge
2022-02-26T02:17:35.7670900Z cmake                     3.21.3               hdbd2f3e_0    conda-forge
2022-02-26T02:17:35.7671320Z compiler-rt               12.0.1               he01351e_0    conda-forge
2022-02-26T02:17:35.7671750Z compiler-rt_osx-64        12.0.1               hd3f61c9_0    conda-forge
2022-02-26T02:17:35.7672270Z compilers                 1.4.0                h694c41f_0    conda-forge
2022-02-26T02:17:35.7672700Z console_bridge            1.0.1                h65a07b1_0    conda-forge
2022-02-26T02:17:35.7673090Z cppzmq                    4.8.1                hf09c4ce_0    conda-forge
2022-02-26T02:17:35.7673500Z curl                      7.81.0               hf45b732_0    conda-forge
2022-02-26T02:17:35.7673930Z cxx-compiler              1.4.0                hbb4e6a2_0    conda-forge
2022-02-26T02:17:35.7674320Z eigen                     3.4.0                h940c156_0    conda-forge
2022-02-26T02:17:35.7674720Z expat                     2.4.6                h96cf925_0    conda-forge
2022-02-26T02:17:35.7675210Z ffmpeg                    4.3.2                hbf27d7b_2    conda-forge
2022-02-26T02:17:35.7675650Z font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
2022-02-26T02:17:35.7676740Z font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
2022-02-26T02:17:35.7677240Z font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
2022-02-26T02:17:35.7677670Z font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
2022-02-26T02:17:35.7678060Z fontconfig                2.13.96              h10f422b_0    conda-forge
2022-02-26T02:17:35.7678660Z fonts-conda-ecosystem     1                             0    conda-forge
2022-02-26T02:17:35.7679170Z fonts-conda-forge         1                             0    conda-forge
2022-02-26T02:17:35.7679560Z fortran-compiler          1.4.0                h46a1860_0    conda-forge
2022-02-26T02:17:35.7680100Z freeimage                 3.18.0               h7d96ac2_7    conda-forge
2022-02-26T02:17:35.7680480Z freetype                  2.10.4               h4cff582_1    conda-forge
2022-02-26T02:17:35.7680910Z fribidi                   1.0.10               hbcb3906_0    conda-forge
2022-02-26T02:17:35.7681340Z gazebo                    11.5.0               hc02bdab_1    conda-forge
2022-02-26T02:17:35.7681720Z gdbm                      1.18                 h8a0c380_2    conda-forge
2022-02-26T02:17:35.7682130Z gdk-pixbuf                2.42.6               h2e6141f_0    conda-forge
2022-02-26T02:17:35.7682930Z gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
2022-02-26T02:17:35.7683430Z gfortran                  9.3.0               h768ea0c_15    conda-forge
2022-02-26T02:17:35.7683860Z gfortran_impl_osx-64      9.3.0               h9cc0e5e_23    conda-forge
2022-02-26T02:17:35.7684250Z gfortran_osx-64           9.3.0               h18f7dce_15    conda-forge
2022-02-26T02:17:35.7684820Z giflib                    5.2.1                hbcb3906_2    conda-forge
2022-02-26T02:17:35.7685200Z glew                      2.1.0                h046ec9c_2    conda-forge
2022-02-26T02:17:35.7685600Z glfw                      3.3.6                h0d85af4_0    conda-forge
2022-02-26T02:17:35.7686020Z gmp                       6.2.1                h2e338ed_0    conda-forge
2022-02-26T02:17:35.7686380Z gnutls                    3.6.13               h756fd2b_1    conda-forge
2022-02-26T02:17:35.7686790Z graphite2                 1.3.13            h2e338ed_1001    conda-forge
2022-02-26T02:17:35.7687160Z graphviz                  2.50.0               h77de9ca_1    conda-forge
2022-02-26T02:17:35.7687570Z gsl                       2.7                  h93259b0_0    conda-forge
2022-02-26T02:17:35.7688110Z gtk2                      2.24.33              h675d97a_1    conda-forge
2022-02-26T02:17:35.7688500Z gts                       0.7.6                hccb3bdf_2    conda-forge
2022-02-26T02:17:35.7688870Z harfbuzz                  2.9.1                h159f659_1    conda-forge
2022-02-26T02:17:35.7689280Z hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
2022-02-26T02:17:35.7689650Z icu                       68.2                 he49afe7_0    conda-forge
2022-02-26T02:17:35.7690300Z ilmbase                   2.5.5                hfab91a5_0    conda-forge
2022-02-26T02:17:35.7690740Z ipopt                     3.14.4               hc501a57_0    conda-forge
2022-02-26T02:17:35.7691120Z irrlicht                  1.8.5                he00d70a_2    conda-forge
2022-02-26T02:17:35.7691540Z isl                       0.22.1               hb1e8313_2    conda-forge
2022-02-26T02:17:35.7691910Z jasper                    1.900.1           h636a363_1006    conda-forge
2022-02-26T02:17:35.7692600Z jbig                      2.1               h0d85af4_2003    conda-forge
2022-02-26T02:17:35.7693230Z jpeg                      9e                   h0d85af4_0    conda-forge
2022-02-26T02:17:35.7693700Z jsoncpp                   1.9.4                h940c156_3    conda-forge
2022-02-26T02:17:35.7694120Z jxrlib                    1.1                  h35c211d_2    conda-forge
2022-02-26T02:17:35.7694480Z krb5                      1.19.2               hcfbf3a7_3    conda-forge
2022-02-26T02:17:35.7695330Z lame                      3.100             h35c211d_1001    conda-forge
2022-02-26T02:17:35.7695800Z lcms2                     2.12                 h577c468_0    conda-forge
2022-02-26T02:17:35.7696160Z ld64                      609                  hd2e7500_6    conda-forge
2022-02-26T02:17:35.7696570Z ld64_osx-64               609                  hc6b1d1e_6    conda-forge
2022-02-26T02:17:35.7696920Z lerc                      3.0                  he49afe7_0    conda-forge
2022-02-26T02:17:35.7697350Z libblas                   3.9.0           13_osx64_openblas    conda-forge
2022-02-26T02:17:35.7697770Z libcblas                  3.9.0           13_osx64_openblas    conda-forge
2022-02-26T02:17:35.7698150Z libccd                    2.1                  he49afe7_1    conda-forge
2022-02-26T02:17:35.7698570Z libclang                  11.1.0          default_he082bbe_1    conda-forge
2022-02-26T02:17:35.7698960Z libclang-cpp12            12.0.1          default_he082bbe_4    conda-forge
2022-02-26T02:17:35.7699400Z libcurl                   7.81.0               hf45b732_0    conda-forge
2022-02-26T02:17:35.7699810Z libcxx                    12.0.1               habf9029_1    conda-forge
2022-02-26T02:17:35.7700180Z libdeflate                1.10                 h0d85af4_0    conda-forge
2022-02-26T02:17:35.7700870Z libedit                   3.1.20191231         h0678c8f_2    conda-forge
2022-02-26T02:17:35.7701230Z libev                     4.33                 haf1e3a3_1    conda-forge
2022-02-26T02:17:35.7701640Z libffi                    3.4.2                h0d85af4_5    conda-forge
2022-02-26T02:17:35.7702200Z libgd                     2.3.3                h311d3fc_0    conda-forge
2022-02-26T02:17:35.7702650Z libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
2022-02-26T02:17:35.7703100Z libgfortran-devel_osx-64  9.3.0               h6c81a4c_23    conda-forge
2022-02-26T02:17:35.7703480Z libgfortran5              9.3.0               h6c81a4c_23    conda-forge
2022-02-26T02:17:35.7703920Z libglib                   2.70.2               hf1fb8c0_4    conda-forge
2022-02-26T02:17:35.7704330Z libiconv                  1.16                 haf1e3a3_0    conda-forge
2022-02-26T02:17:35.7704720Z libignition-cmake2        2.11.0               h96cf925_0    conda-forge
2022-02-26T02:17:35.7705150Z libignition-common3       3.11.1               hca1d88e_0    conda-forge
2022-02-26T02:17:35.7705540Z libignition-fuel-tools4   4.3.0                h65c21be_2    conda-forge
2022-02-26T02:17:35.7705990Z libignition-math6         6.10.0               hcd9eead_0    conda-forge
2022-02-26T02:17:35.7706420Z libignition-msgs5         5.3.0                hf2f16fe_6    conda-forge
2022-02-26T02:17:35.7706810Z libignition-tools1        1.4.1                hcdefd0e_2    conda-forge
2022-02-26T02:17:35.7707240Z libignition-transport8    8.1.0                h99b938e_6    conda-forge
2022-02-26T02:17:35.7707630Z libjpeg-turbo             2.1.1                h0d85af4_0    conda-forge
2022-02-26T02:17:35.7708080Z liblapack                 3.9.0           13_osx64_openblas    conda-forge
2022-02-26T02:17:35.7708510Z liblapacke                3.9.0           13_osx64_openblas    conda-forge
2022-02-26T02:17:35.7708900Z libllvm11                 11.1.0               hd011deb_3    conda-forge
2022-02-26T02:17:35.7709310Z libllvm12                 12.0.1               hd011deb_2    conda-forge
2022-02-26T02:17:35.7709680Z libmatio                  1.5.21               h791987c_0    conda-forge
2022-02-26T02:17:35.7710100Z libnghttp2                1.47.0               h942079c_0    conda-forge
2022-02-26T02:17:35.7710500Z libode                    0.16.2               h9fcab8e_9    conda-forge
2022-02-26T02:17:35.7710890Z libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
2022-02-26T02:17:35.7711310Z libopencv                 4.5.2            py39h49f8dfa_0    conda-forge
2022-02-26T02:17:35.7711680Z libpng                    1.6.37               h7cec526_2    conda-forge
2022-02-26T02:17:35.7712350Z libpq                     13.5                 hea3049e_1    conda-forge
2022-02-26T02:17:35.7712840Z libprotobuf               3.15.8               hcf210ce_1    conda-forge
2022-02-26T02:17:35.7713220Z libraw                    0.20.2               hefd3b78_1    conda-forge
2022-02-26T02:17:35.7713620Z librsvg                   2.52.5               h02b643e_1    conda-forge
2022-02-26T02:17:35.7713980Z libsdformat               9.3.0                h6955478_5    conda-forge
2022-02-26T02:17:35.7714390Z libsodium                 1.0.18               hbcb3906_1    conda-forge
2022-02-26T02:17:35.7714790Z libssh2                   1.10.0               h52ee1ee_2    conda-forge
2022-02-26T02:17:35.7715170Z libtar                    1.2.20            h0d85af4_1004    conda-forge
2022-02-26T02:17:35.7715560Z libtiff                   4.3.0                h17f2ce3_3    conda-forge
2022-02-26T02:17:35.7715920Z libtool                   2.4.6             he49afe7_1008    conda-forge
2022-02-26T02:17:35.7716340Z libuv                     1.43.0               h0d85af4_0    conda-forge
2022-02-26T02:17:35.7716740Z libwebp                   1.2.2                h28dabe5_0    conda-forge
2022-02-26T02:17:35.7717110Z libwebp-base              1.2.2                h0d85af4_1    conda-forge
2022-02-26T02:17:35.7717760Z libxcb                    1.13              h0d85af4_1004    conda-forge
2022-02-26T02:17:35.7718120Z libxml2                   2.9.12               h93ec3fd_0    conda-forge
2022-02-26T02:17:35.7718540Z libzip                    1.8.0                h8b0c345_1    conda-forge
2022-02-26T02:17:35.7718940Z libzlib                   1.2.11            h9173be1_1013    conda-forge
2022-02-26T02:17:35.7719310Z llvm-openmp               13.0.1               hda6cdc1_0    conda-forge
2022-02-26T02:17:35.7719720Z llvm-tools                12.0.1               hd011deb_2    conda-forge
2022-02-26T02:17:35.7720080Z lua                       5.4.4                hf9dbe3d_0    conda-forge
2022-02-26T02:17:35.7720490Z lz4-c                     1.9.3                he49afe7_1    conda-forge
2022-02-26T02:17:35.7720900Z make                      4.3                  h22f3db7_1    conda-forge
2022-02-26T02:17:35.7721280Z metis                     5.1.0             h2e338ed_1006    conda-forge
2022-02-26T02:17:35.7721690Z mpc                       1.2.1                hbb51d92_0    conda-forge
2022-02-26T02:17:35.7722040Z mpfr                      4.1.0                h0f52abe_1    conda-forge
2022-02-26T02:17:35.7722460Z mumps-include             5.2.1               h694c41f_10    conda-forge
2022-02-26T02:17:35.7722880Z mumps-seq                 5.2.1               h805a9e9_10    conda-forge
2022-02-26T02:17:35.7723260Z mysql-common              8.0.28               h694c41f_0    conda-forge
2022-02-26T02:17:35.7723660Z mysql-libs                8.0.28               h115446f_0    conda-forge
2022-02-26T02:17:35.7724030Z ncurses                   6.3                  he49afe7_0    conda-forge
2022-02-26T02:17:35.7724440Z nettle                    3.6                  hedd7734_0    conda-forge
2022-02-26T02:17:35.7724850Z ninja                     1.10.2               h940c156_1    conda-forge
2022-02-26T02:17:35.7725220Z nlohmann_json             3.10.5               he49afe7_0    conda-forge
2022-02-26T02:17:35.7725640Z nspr                      4.32                 hcd9eead_1    conda-forge
2022-02-26T02:17:35.7725990Z nss                       3.74                 h31e2bf1_0    conda-forge
2022-02-26T02:17:35.7726410Z numpy                     1.22.2           py39h9d9ce41_0    conda-forge
2022-02-26T02:17:35.7726770Z ogre                      1.10.12              hefd5428_7    conda-forge
2022-02-26T02:17:35.7727180Z opencv                    4.5.2            py39h6e9494a_0    conda-forge
2022-02-26T02:17:35.7727580Z openexr                   2.5.5                h7fa7ffa_0    conda-forge
2022-02-26T02:17:35.7727950Z openh264                  2.1.1                hfd3ada9_0    conda-forge
2022-02-26T02:17:35.7728370Z openjpeg                  2.4.0                h6e7aa92_1    conda-forge
2022-02-26T02:17:35.7728980Z openssl                   1.1.1l               h0d85af4_0    conda-forge
2022-02-26T02:17:35.7729470Z pango                     1.48.10              ha05cd14_1    conda-forge
2022-02-26T02:17:35.7729880Z pcre                      8.45                 he49afe7_0    conda-forge
2022-02-26T02:17:35.7730360Z pip                       22.0.3             pyhd8ed1ab_0    conda-forge
2022-02-26T02:17:35.7730770Z pixman                    0.40.0               hbcb3906_0    conda-forge
2022-02-26T02:17:35.7731140Z pkg-config                0.29.2            h31203cd_1008    conda-forge
2022-02-26T02:17:35.7731560Z portaudio                 19.6.0               he49afe7_4    conda-forge
2022-02-26T02:17:35.7731980Z protobuf                  3.15.8           py39h9fcab8e_0    conda-forge
2022-02-26T02:17:35.7732490Z pthread-stubs             0.4               hc929b4f_1001    conda-forge
2022-02-26T02:17:35.7733060Z pugixml                   1.11.4               he49afe7_0    conda-forge
2022-02-26T02:17:35.7733450Z py-opencv                 4.5.2            py39h71a6800_0    conda-forge
2022-02-26T02:17:35.7733880Z pybind11                  2.9.1            py39hf018cea_0    conda-forge
2022-02-26T02:17:35.7734550Z pybind11-global           2.9.1            py39hf018cea_0    conda-forge
2022-02-26T02:17:35.7734950Z python                    3.9.10          h1dd9edd_2_cpython    conda-forge
2022-02-26T02:17:35.7735400Z python_abi                3.9                      2_cp39    conda-forge
2022-02-26T02:17:35.7735770Z qt                        5.12.9               h126340a_4    conda-forge
2022-02-26T02:17:35.7736160Z qwt                       6.1.6                h3050948_0    conda-forge
2022-02-26T02:17:35.7736550Z readline                  8.1                  h05e3726_0    conda-forge
2022-02-26T02:17:35.7736920Z rhash                     1.4.1                h35c211d_0    conda-forge
2022-02-26T02:17:35.7737320Z ruby                      3.1.1                h586acb3_0    conda-forge
2022-02-26T02:17:35.7737700Z scotch                    6.0.9                h9f43b6f_1    conda-forge
2022-02-26T02:17:35.7738110Z sdl                       1.2.15               he49afe7_1    conda-forge
2022-02-26T02:17:35.7738510Z sdl2                      2.0.18               he49afe7_0    conda-forge
2022-02-26T02:17:35.7738880Z setuptools                60.9.3           py39h6e9494a_0    conda-forge
2022-02-26T02:17:35.7739300Z sigtool                   0.1.3                h57ddcff_0    conda-forge
2022-02-26T02:17:35.7739660Z six                       1.16.0             pyh6c4a22f_0    conda-forge
2022-02-26T02:17:35.7740070Z spdlog                    1.9.2                h940c156_1    conda-forge
2022-02-26T02:17:35.7740460Z sqlite                    3.37.0               h23a322b_0    conda-forge
2022-02-26T02:17:35.7740820Z swig                      4.0.2                hce5123c_2    conda-forge
2022-02-26T02:17:35.7741220Z tapi                      1100.0.11            h9ce4665_0    conda-forge
2022-02-26T02:17:35.7741590Z tbb                       2020.2               h940c156_4    conda-forge
2022-02-26T02:17:35.7742000Z tbb-devel                 2020.2               h940c156_4    conda-forge
2022-02-26T02:17:35.7742400Z tinyxml                   2.6.2                h65a07b1_2    conda-forge
2022-02-26T02:17:35.7742760Z tinyxml2                  8.0.0                h1c7c35f_1    conda-forge
2022-02-26T02:17:35.7743180Z tk                        8.6.12               h5dbffcc_0    conda-forge
2022-02-26T02:17:35.7743540Z tzdata                    2021e                he74cb21_0    conda-forge
2022-02-26T02:17:35.7743940Z unixodbc                  2.3.9                hd863c23_0    conda-forge
2022-02-26T02:17:35.7744340Z urdfdom                   2.3.5                h940c156_0    conda-forge
2022-02-26T02:17:35.7744710Z urdfdom_headers           1.0.5                h940c156_2    conda-forge
2022-02-26T02:17:35.7745120Z wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
2022-02-26T02:17:35.7745750Z x264                      1!161.3030           h0d85af4_1    conda-forge
2022-02-26T02:17:35.7746230Z xorg-fixesproto           5.0               h0d85af4_1002    conda-forge
2022-02-26T02:17:35.7746660Z xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
2022-02-26T02:17:35.7747040Z xorg-libice               1.0.10               h0d85af4_0    conda-forge
2022-02-26T02:17:35.7747440Z xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
2022-02-26T02:17:35.7747850Z xorg-libx11               1.7.2                h0d85af4_0    conda-forge
2022-02-26T02:17:35.7748210Z xorg-libxau               1.0.9                h35c211d_0    conda-forge
2022-02-26T02:17:35.7748610Z xorg-libxaw               1.0.14               h0d85af4_1    conda-forge
2022-02-26T02:17:35.7749010Z xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
2022-02-26T02:17:35.7750030Z xorg-libxext              1.3.4                h0d85af4_1    conda-forge
2022-02-26T02:17:35.7750470Z xorg-libxfixes            5.0.3             h0d85af4_1004    conda-forge
2022-02-26T02:17:35.7750920Z xorg-libxmu               1.1.3                h0d85af4_0    conda-forge
2022-02-26T02:17:35.7751630Z xorg-libxpm               3.5.13               h0d85af4_0    conda-forge
2022-02-26T02:17:35.7752030Z xorg-libxrender           0.9.10            h0d85af4_1003    conda-forge
2022-02-26T02:17:35.7752560Z xorg-libxt                1.2.1                h0d85af4_2    conda-forge
2022-02-26T02:17:35.7752970Z xorg-renderproto          0.11.1            h0d85af4_1002    conda-forge
2022-02-26T02:17:35.7753420Z xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
2022-02-26T02:17:35.7753840Z xorg-xproto               7.0.31            h35c211d_1007    conda-forge
2022-02-26T02:17:35.7769150Z xz                        5.2.5                haf1e3a3_1    conda-forge
2022-02-26T02:17:35.7769530Z yaml                      0.2.5                h0d85af4_2    conda-forge
2022-02-26T02:17:35.7769960Z zeromq                    4.3.4                he49afe7_1    conda-forge
2022-02-26T02:17:35.7770370Z zlib                      1.2.11            h9173be1_1013    conda-forge
2022-02-26T02:17:35.7770750Z zstd                      1.5.2                h582d3a0_0    conda-forge
2022-02-26T02:17:35.7771180Z zziplib                   0.13.69              h5dbffcc_1    conda-forge
~~~

**Comment by traversaro** [comment]
I looked a bit in the history of the CI, and an older opencv/protobuf was selected since 11 days ago. The nightly job 11 days ago was still installing the latest protobuf (3.19), while 10 days ago protobuf 3.15 has started being installed. I think that if we look into that, we may found the source of the problem.

**Comment by traversaro** [comment]
Looking back at history of PR, some related PR could be:
* https://github.com/robotology/robotology-superbuild/pull/1035
* https://github.com/robotology/robotology-superbuild/pull/1025

We can try to revert both and check if something changes.

**Comment by traversaro** [comment]
By looking better to the history of the PRs, the change is clearly due to https://github.com/robotology/robotology-superbuild/pull/1025 .

**Comment by traversaro** [comment]
We added a workaround for this in https://github.com/robotology/robotology-superbuild/pull/1049 . Eventually we should get rid of this by solving https://github.com/conda-forge/gazebo-feedstock/issues/119 . Furthermore, for this kind of debugging is really important we move to conda-forge as many packages as we can, especially the one that take a lot of time to build, so we should progress in https://github.com/robotology/robotology-superbuild/issues/752 .
