### ISSUE TITLE
2022.02 release CI dry run

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1046]
I did a 2022.02 release dry run in:
* C++ CI: https://github.com/traversaro/robotology-superbuild/actions/runs/1900139386
* Generate Conda Packages CI: https://github.com/traversaro/robotology-superbuild/actions/runs/1900139387

To check if the CI (that is quite more complex since https://github.com/robotology/robotology-superbuild/pull/1030) is working fine.
The release dry run will not interfere with the regular releases as it is done in a fork.

**Comment by traversaro** [comment]
These are the problems:

## P1

Conda packages generation on macOS, as described in https://github.com/robotology/robotology-superbuild/issues/1041 .

## P2 

Conda **meta**packaages generation on Windows and Linux:
~~~
2022-02-25T22:18:40.6574848Z conda-forge/linux-64     Using cache
2022-02-25T22:18:40.6599134Z conda-forge/noarch       Using cache
2022-02-25T22:18:41.0667520Z Reloading output folder: /usr/share/miniconda/envs/test/conda-bld
2022-02-25T22:18:41.1710391Z Reloading output folder: /usr/share/miniconda/envs/test/conda-bld
2022-02-25T22:18:41.3220950Z BUILD START: ['robotology-distro-all-2022.02.0-ha770c72_43.tar.bz2']
2022-02-25T22:18:41.3221854Z Reloading output folder: /usr/share/miniconda/envs/test/conda-bld
2022-02-25T22:18:41.4236448Z Reloading output folder: /usr/share/miniconda/envs/test/conda-bld
2022-02-25T22:18:42.4082529Z Mamba failed to solve:
2022-02-25T22:18:42.4083178Z  - blocktest 2.3.4.*
2022-02-25T22:18:42.4083544Z  - yarp-matlab-bindings 3.6.0.*
2022-02-25T22:18:42.4083926Z  - whole-body-estimators 0.6.1.*
2022-02-25T22:18:42.4084304Z  - gazebo-yarp-plugins 4.1.2.*
2022-02-25T22:18:42.4084617Z  - wb-toolbox 5.5.0.*
2022-02-25T22:18:42.4084979Z  - unicycle-footstep-planner 0.4.1.*
2022-02-25T22:18:42.4085340Z  - yarp-telemetry 0.4.0.*
2022-02-25T22:18:42.4085664Z  - yarp-device-xsensmt 0.1.1.*
2022-02-25T22:18:42.4085985Z  - icub-tests 1.22.0.*
2022-02-25T22:18:42.4086317Z  - icub-contrib-common 1.19.0.*
2022-02-25T22:18:42.4086653Z  - idyntree-yarp-tools 0.0.4.*
2022-02-25T22:18:42.4087011Z  - robots-configuration 1.23.0.*
2022-02-25T22:18:42.4087332Z  - osqp-matlab 0.6.2.0.*
2022-02-25T22:18:42.4087693Z  - human-dynamics-estimation 2.4.0.*
2022-02-25T22:18:42.4088087Z  - idyntree-matlab-bindings 5.0.1.*
2022-02-25T22:18:42.4088411Z  - human-gazebo 1.0.*
2022-02-25T22:18:42.4088714Z  - event-driven 1.6.*
2022-02-25T22:18:42.4089064Z  - forcetorque-yarp-devices 0.2.0.*
2022-02-25T22:18:42.4089384Z  - matio-cpp 0.1.1.*
2022-02-25T22:18:42.4089682Z  - qhull 2020.2.*
2022-02-25T22:18:42.4089948Z  - qpoases 3.2.0.1.*
2022-02-25T22:18:42.4090652Z  - lie-group-controllers 0.1.1.*
2022-02-25T22:18:42.4090992Z  - wearables 1.2.2.*
2022-02-25T22:18:42.4091311Z  - ycm-cmake-modules 0.13.0.*
2022-02-25T22:18:42.4091679Z  - blocktest-yarp-plugins 1.1.2.*
2022-02-25T22:18:42.4092036Z  - icub-basic-demos 1.21.0.*
2022-02-25T22:18:42.4092325Z  - casadi 3.5.5.*
2022-02-25T22:18:42.4092664Z  - robot-testing-framework 2.0.1.*
2022-02-25T22:18:42.4092977Z  - idyntree 5.0.1.*
2022-02-25T22:18:42.4093278Z  - icub-models 1.22.1.*
2022-02-25T22:18:42.4093575Z  - libosqp 0.6.2.*
2022-02-25T22:18:42.4093844Z  - speech 1.1.0.*
2022-02-25T22:18:42.4094210Z  - bipedal-locomotion-framework 0.6.0.*
2022-02-25T22:18:42.4094559Z  - cppad 20220000.1.*
2022-02-25T22:18:42.4094827Z  - manif 0.0.4.*
2022-02-25T22:18:42.4095115Z  - icub-main 1.24.0.*
2022-02-25T22:18:42.4095401Z  - funny-things 2.0.0.*
2022-02-25T22:18:42.4095707Z  - blockfactory 0.8.2.*
2022-02-25T22:18:42.4096048Z  - icub-firmware-shared 1.24.0.*
2022-02-25T22:18:42.4096419Z  - matlab-whole-body-simulator 2.0.0.*
2022-02-25T22:18:42.4096769Z  - osqp-eigen 0.7.0.*
2022-02-25T22:18:42.4097308Z  - walking-teleoperation 1.2.0.*
2022-02-25T22:18:42.4097661Z  - whole-body-controllers 2.5.6.*
2022-02-25T22:18:42.4097977Z  - yarp 3.6.0.*
2022-02-25T22:18:42.4098299Z  - walking-controllers 0.5.0.*
2022-02-25T22:18:42.4098649Z  - casadi-matlab-bindings 3.5.5.1.*
2022-02-25T22:18:42.4098842Z 
2022-02-25T22:18:42.4098938Z with channels:
2022-02-25T22:18:42.4099187Z  - local
2022-02-25T22:18:42.4099449Z  - conda-forge
2022-02-25T22:18:42.4099717Z  - robotology
2022-02-25T22:18:42.4099858Z 
2022-02-25T22:18:42.4100334Z The reported errors are:
2022-02-25T22:18:42.4100987Z - Encountered problems while solving:
2022-02-25T22:18:42.4101745Z -   - package bipedal-locomotion-framework-0.6.0-py38h2327190_41 requires yarp-telemetry >=0.3.0,<0.3.1.0a0, but none of the providers can be installed
2022-02-25T22:18:42.4102230Z - 
2022-02-25T22:18:42.4102999Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4103273Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4103601Z robotology/linux-64       
2022-02-25T22:18:42.4103871Z robotology/noarch         
2022-02-25T22:18:42.4104122Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4104387Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4104647Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4104891Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4105156Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4105418Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4105662Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4105925Z usr/share/miniconda/envs  
2022-02-25T22:18:42.4156610Z Traceback (most recent call last):
2022-02-25T22:18:42.4157460Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 123, in mamba_get_install_actions
2022-02-25T22:18:42.4157945Z     solution = solver.solve_for_action(_specs, prefix)
2022-02-25T22:18:42.4158560Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve_for_action
2022-02-25T22:18:42.4158963Z     t = self.solve(specs)
2022-02-25T22:18:42.4159498Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/core/solver.py", line 216, in solve
2022-02-25T22:18:42.4159956Z     raise RuntimeError("Solver could not find solution." + error_string)
2022-02-25T22:18:42.4160352Z RuntimeError: Solver could not find solution.Mamba failed to solve:
2022-02-25T22:18:42.4160729Z  - blocktest 2.3.4.*
2022-02-25T22:18:42.4161068Z  - yarp-matlab-bindings 3.6.0.*
2022-02-25T22:18:42.4161421Z  - whole-body-estimators 0.6.1.*
2022-02-25T22:18:42.4161783Z  - gazebo-yarp-plugins 4.1.2.*
2022-02-25T22:18:42.4162109Z  - wb-toolbox 5.5.0.*
2022-02-25T22:18:42.4162452Z  - unicycle-footstep-planner 0.4.1.*
2022-02-25T22:18:42.4162811Z  - yarp-telemetry 0.4.0.*
2022-02-25T22:18:42.4163136Z  - yarp-device-xsensmt 0.1.1.*
2022-02-25T22:18:42.4163462Z  - icub-tests 1.22.0.*
2022-02-25T22:18:42.4163793Z  - icub-contrib-common 1.19.0.*
2022-02-25T22:18:42.4164128Z  - idyntree-yarp-tools 0.0.4.*
2022-02-25T22:18:42.4164746Z  - robots-configuration 1.23.0.*
2022-02-25T22:18:42.4165097Z  - osqp-matlab 0.6.2.0.*
2022-02-25T22:18:42.4165440Z  - human-dynamics-estimation 2.4.0.*
2022-02-25T22:18:42.4165831Z  - idyntree-matlab-bindings 5.0.1.*
2022-02-25T22:18:42.4166169Z  - human-gazebo 1.0.*
2022-02-25T22:18:42.4166457Z  - event-driven 1.6.*
2022-02-25T22:18:42.4166811Z  - forcetorque-yarp-devices 0.2.0.*
2022-02-25T22:18:42.4167132Z  - matio-cpp 0.1.1.*
2022-02-25T22:18:42.4167422Z  - qhull 2020.2.*
2022-02-25T22:18:42.4167707Z  - qpoases 3.2.0.1.*
2022-02-25T22:18:42.4168029Z  - lie-group-controllers 0.1.1.*
2022-02-25T22:18:42.4168357Z  - wearables 1.2.2.*
2022-02-25T22:18:42.4168680Z  - ycm-cmake-modules 0.13.0.*
2022-02-25T22:18:42.4169026Z  - blocktest-yarp-plugins 1.1.2.*
2022-02-25T22:18:42.4169378Z  - icub-basic-demos 1.21.0.*
2022-02-25T22:18:42.4169663Z  - casadi 3.5.5.*
2022-02-25T22:18:42.4170002Z  - robot-testing-framework 2.0.1.*
2022-02-25T22:18:42.4170323Z  - idyntree 5.0.1.*
2022-02-25T22:18:42.4170604Z  - icub-models 1.22.1.*
2022-02-25T22:18:42.4170897Z  - libosqp 0.6.2.*
2022-02-25T22:18:42.4171179Z  - speech 1.1.0.*
2022-02-25T22:18:42.4171529Z  - bipedal-locomotion-framework 0.6.0.*
2022-02-25T22:18:42.4171875Z  - cppad 20220000.1.*
2022-02-25T22:18:42.4172141Z  - manif 0.0.4.*
2022-02-25T22:18:42.4172426Z  - icub-main 1.24.0.*
2022-02-25T22:18:42.4172723Z  - funny-things 2.0.0.*
2022-02-25T22:18:42.4173013Z  - blockfactory 0.8.2.*
2022-02-25T22:18:42.4173349Z  - icub-firmware-shared 1.24.0.*
2022-02-25T22:18:42.4173731Z  - matlab-whole-body-simulator 2.0.0.*
2022-02-25T22:18:42.4174058Z  - osqp-eigen 0.7.0.*
2022-02-25T22:18:42.4174394Z  - walking-teleoperation 1.2.0.*
2022-02-25T22:18:42.4174746Z  - whole-body-controllers 2.5.6.*
2022-02-25T22:18:42.4175058Z  - yarp 3.6.0.*
2022-02-25T22:18:42.4175373Z  - walking-controllers 0.5.0.*
2022-02-25T22:18:42.4175724Z  - casadi-matlab-bindings 3.5.5.1.*
2022-02-25T22:18:42.4176028Z 
2022-02-25T22:18:42.4176123Z with channels:
2022-02-25T22:18:42.4176392Z  - local
2022-02-25T22:18:42.4176640Z  - conda-forge
2022-02-25T22:18:42.4177109Z  - robotology
2022-02-25T22:18:42.4177252Z 
2022-02-25T22:18:42.4177348Z The reported errors are:
2022-02-25T22:18:42.4177706Z - Encountered problems while solving:
2022-02-25T22:18:42.4178432Z -   - package bipedal-locomotion-framework-0.6.0-py38h2327190_41 requires yarp-telemetry >=0.3.0,<0.3.1.0a0, but none of the providers can be installed
2022-02-25T22:18:42.4178907Z - 
2022-02-25T22:18:42.4179033Z 
2022-02-25T22:18:42.4179227Z During handling of the above exception, another exception occurred:
2022-02-25T22:18:42.4179459Z 
2022-02-25T22:18:42.4179585Z Traceback (most recent call last):
2022-02-25T22:18:42.4180060Z   File "/usr/share/miniconda/envs/test/bin/conda-mambabuild", line 10, in <module>
2022-02-25T22:18:42.4180404Z     sys.exit(main())
2022-02-25T22:18:42.4180934Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 215, in main
2022-02-25T22:18:42.4181324Z     call_conda_build(action, config)
2022-02-25T22:18:42.4181899Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
2022-02-25T22:18:42.4182300Z     result = api.build(
2022-02-25T22:18:42.4182810Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
2022-02-25T22:18:42.4183180Z     return build_tree(
2022-02-25T22:18:42.4183717Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 3088, in build_tree
2022-02-25T22:18:42.4184129Z     packages_from_this = build(metadata, stats,
2022-02-25T22:18:42.4184694Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 2128, in build
2022-02-25T22:18:42.4185107Z     create_build_envs(top_level_pkg, notest)
2022-02-25T22:18:42.4185677Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 1985, in create_build_envs
2022-02-25T22:18:42.4186236Z     environ.get_install_actions(m.config.test_prefix,
2022-02-25T22:18:42.4186886Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 125, in mamba_get_install_actions
2022-02-25T22:18:42.4187322Z     conflict_packages = parse_problems(str(e))
2022-02-25T22:18:42.4187912Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 40, in parse_problems
2022-02-25T22:18:42.4188314Z     assert words[1] == "package"
2022-02-25T22:18:42.4188559Z AssertionError
2022-02-25T22:18:42.6095675Z ##[error]Process completed with exit code 1.
2022-02-25T22:18:42.6343221Z Post job cleanup.
2022-02-25T22:18:42.8413069Z [command]/usr/bin/git version
2022-02-25T22:18:42.8467791Z git version 2.35.1
2022-02-25T22:18:42.8536280Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-02-25T22:18:42.8927444Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-02-25T22:18:42.8928303Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-02-25T22:18:42.8964686Z http.https://github.com/.extraheader
2022-02-25T22:18:42.8965471Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-02-25T22:18:42.9006127Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-02-25T22:18:43.0015317Z Cleaning up orphan processes
~~~

## P3 

Windows-vcpkg build failure:
~~~
2022-02-25T19:52:07.7689131Z     Generating Code...
2022-02-25T19:52:11.1221049Z C:\robotology-superbuild\src\HumanDynamicsEstimation\HumanDynamicsEstimationLibrary\algorithms\src\InverseVelocityKinematics.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [C:\robotology-superbuild\build\src\HumanDynamicsEstimation\HumanDynamicsEstimationLibrary\algorithms\algorithms.vcxproj] [C:\robotology-superbuild\build\HumanDynamicsEstimation.vcxproj]
2022-02-25T19:52:11.3808054Z     Building Custom Rule C:/robotology-superbuild/src/HumanDynamicsEstimation/publishers/HumanStatePublisher/CMakeLists.txt
2022-02-25T19:52:11.4971355Z     HumanStatePublisher.cpp
2022-02-25T19:52:11.9694362Z C:\robotology\robotology\include\yarp/os/api.h(53): warning : "The YARP::YARP_OS target is deprecated. Use YARP::YARP_os instead" [C:\robotology-superbuild\build\src\HumanDynamicsEstimation\publishers\HumanStatePublisher\HumanStatePublisher.vcxproj] [C:\robotology-superbuild\build\HumanDynamicsEstimation.vcxproj]
2022-02-25T19:52:12.0521509Z C:\robotology\robotology\include\yarp/dev/Wrapper.h(14): warning : "<yarp/dev/Wrapper.h> file is deprecated. Use <yarp/dev/IWrapper.h> and <yarp/dev/IMultipleWrapper.h> instead" [C:\robotology-superbuild\build\src\HumanDynamicsEstimation\publishers\HumanStatePublisher\HumanStatePublisher.vcxproj] [C:\robotology-superbuild\build\HumanDynamicsEstimation.vcxproj]
~~~

**Comment by traversaro** [comment]
P3 is quite easy to solve, even if it requires a change in HDE. Interestingly it seems we already solved it (see https://github.com/robotology/robotology-superbuild/pull/352#issuecomment-589662805), let's see what went wrong.

**Comment by traversaro** [comment]
I suspect P2 is related to https://github.com/robotology/robotology-superbuild/pull/1047, as an older cppad was forced, and so an older bipedal-locomotion-framework is used. I try to trigger a new dry run after updating the version to see if this fixes the problem.

**Comment by traversaro** [comment]
> I suspect P2 is related to #1047, as an older cppad was forced, and so an older bipedal-locomotion-framework is used. I try to trigger a new dry run after updating the version to see if this fixes the problem:
> 
>     * https://github.com/traversaro/robotology-superbuild/actions/runs/1903440491

Indeed that solved P2, at least for Windows and Linux. I just tried to install (note that I used 2022.03.0 as this is the experimental version that I created):
~~~
mamba create -n gypnew -c conda-forge -c robotology-staging robotology-distro=2022.03.0 gazebo-yarp-plugins
~~~

And it is working fine. The problem is that qt 5.12.9 *_5 is installed, so we would be affected by the problem described in https://github.com/conda-forge/gazebo-feedstock/issues/119 . At least for 2022.02 it probably make sense to pin qt also in the robotology-distro-* metapackages, even if I am not sure if that will work for macOS.

**Comment by traversaro** [comment]
New dry run in https://github.com/traversaro/robotology-superbuild/runs/5346558463 failed due to metapackages and the combination of https://github.com/robotology/robotology-superbuild/pull/1049 and pinning qt in the metapackages. Better to find a better solution soon, testing now via https://github.com/traversaro/github-actions-tmate/actions .

**Comment by traversaro** [comment]
By manually installing a possible compromise of pin is gazebo=11.9 (not 1.10 that is broken, see ), libopencv=4.5.3 (that is homewever different from the current version pinned in conda-forge, that is 4.5.5) and qt `qt 5.12.9 *_4`, testing this in https://github.com/traversaro/robotology-superbuild/runs/5350794710?check_suite_focus=true (commit https://github.com/traversaro/robotology-superbuild/commit/e27cc8580303bfff92878860d9a9066b275d2212). Hopefully all this manually tweaking should end once we solve (probably with the qt 5.15 update) https://github.com/conda-forge/gazebo-feedstock/issues/119 .

**Comment by traversaro** [comment]
> By manually installing a possible compromise of pin is gazebo=11.9 (not 1.10 that is broken, see ), libopencv=4.5.3 (that is homewever different from the current version pinned in conda-forge, that is 4.5.5) and qt `qt 5.12.9 *_4`, testing this in https://github.com/traversaro/robotology-superbuild/runs/5350794710?check_suite_focus=true (commit [traversaro@e27cc85](https://github.com/traversaro/robotology-superbuild/commit/e27cc8580303bfff92878860d9a9066b275d2212)). Hopefully all this manually tweaking should end once we solve (probably with the qt 5.15 update) [conda-forge/gazebo-feedstock#119](https://github.com/conda-forge/gazebo-feedstock/issues/119) .

Even with those pins, the `robotology-distro-all` package build on macOS is failing with strange errors such as:
~~~
with channels:
 - local
 - conda-forge
 - robotology

The reported errors are:
- Encountered problems while solving:
-   - package matlab-whole-body-simulator-2.0.0-h2cdf049_28 requires wb-toolbox >=5.4.1,<5.4.2.0a0, but none of the providers can be installed
~~~ 
or 
~~~
with channels:
 - local
 - conda-forge
 - robotology

The reported errors are:
- Encountered problems while solving:
-   - package matlab-whole-body-simulator-2.0.0-h2cdf049_28 requires wb-toolbox >=5.4.1,<5.4.2.0a0, but none of the providers can be installed
- 
~~~

For some reason, the mamba solver is picking old version from the robotology channel instead of the one from `local` . As the robotology channel when building `robotology-distro-all`  is only useful for esdcan dependency on Windows, I removed that dependency on macOS a re-started the build, let's see if we get a more informative error now:
* https://github.com/traversaro/robotology-superbuild/runs/5352724182

**Comment by traversaro** [comment]
In the end, we went for the modifications in https://github.com/robotology/robotology-superbuild/pull/1049, disabling for now the generation of metapackages on macOS .
