### ISSUE TITLE
generate-conda-package job failed

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1315]
Since a few weeks, the generate-conda-package job is failing.

**Comment by traversaro** [comment]
On Ubuntu the build is failing with:
~~~
2022-12-06T03:10:57.6840147Z INFO:conda_build.metadata:Attempting to finalize metadata for find-superquadric
2022-12-06T03:10:57.6840737Z Attempting to finalize metadata for find-superquadric
2022-12-06T03:11:16.6504850Z Collecting package metadata (repodata.json): ...working... done
2022-12-06T03:11:32.2541169Z Solving environment: ...working... done
2022-12-06T03:11:50.4825373Z Collecting package metadata (repodata.json): ...working... done
2022-12-06T03:13:43.5085122Z Solving environment: ...working... failed
2022-12-06T03:13:43.6115593Z Traceback (most recent call last):
2022-12-06T03:13:43.6119093Z   File "/usr/share/miniconda/envs/test/bin/conda-build", line 11, in <module>
2022-12-06T03:13:43.6119954Z     sys.exit(main())
2022-12-06T03:13:43.6121074Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 494, in main
2022-12-06T03:13:43.6121721Z     execute(sys.argv[1:])
2022-12-06T03:13:43.6122712Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in execute
2022-12-06T03:13:43.6123359Z     outputs = api.build(
2022-12-06T03:13:43.6124053Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
2022-12-06T03:13:43.6124599Z     return build_tree(
2022-12-06T03:13:43.6176928Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 3094, in build_tree
2022-12-06T03:13:43.6177513Z     packages_from_this = build(metadata, stats,
2022-12-06T03:13:43.6178053Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 2049, in build
2022-12-06T03:13:43.6178501Z     output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
2022-12-06T03:13:43.6179109Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 780, in expand_outputs
2022-12-06T03:13:43.6179598Z     for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
2022-12-06T03:13:43.6180266Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/metadata.py", line 2522, in get_output_metadata_set
2022-12-06T03:13:43.6180689Z     conda_packages = finalize_outputs_pass(
2022-12-06T03:13:43.6181258Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
2022-12-06T03:13:43.6181805Z     fm = finalize_metadata(
2022-12-06T03:13:43.6182297Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 540, in finalize_metadata
2022-12-06T03:13:43.6182696Z     build_unsat, host_unsat = add_upstream_pins(m,
2022-12-06T03:13:43.6183242Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 402, in add_upstream_pins
2022-12-06T03:13:43.6184270Z     host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
2022-12-06T03:13:43.6184918Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 367, in _read_upstream_pin_files
2022-12-06T03:13:43.6185378Z     deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
2022-12-06T03:13:43.6185983Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/render.py", line 132, in get_env_dependencies
2022-12-06T03:13:43.6186446Z     actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
2022-12-06T03:13:43.6187050Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/environ.py", line 796, in get_install_actions
2022-12-06T03:13:43.6187469Z     actions = install_actions(prefix, index, specs, force=True)
2022-12-06T03:13:43.6188168Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/common/io.py", line 86, in decorated
2022-12-06T03:13:43.6188669Z     return f(*args, **kwds)
2022-12-06T03:13:43.6189159Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/plan.py", line 476, in install_actions
2022-12-06T03:13:43.6189592Z     txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
2022-12-06T03:13:43.6190157Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
2022-12-06T03:13:43.6190607Z     unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
2022-12-06T03:13:43.6191179Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/core/solve.py", line 199, in solve_for_diff
2022-12-06T03:13:43.6191640Z     final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
2022-12-06T03:13:43.6192233Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/core/solve.py", line 317, in solve_final_state
2022-12-06T03:13:43.6192585Z     ssc = self._add_specs(ssc)
2022-12-06T03:13:43.6193079Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/core/solve.py", line 711, in _add_specs
2022-12-06T03:13:43.6193490Z     conflicts = ssc.r.get_conflicting_specs(tuple(MatchSpec(_)
2022-12-06T03:13:43.6194052Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/resolve.py", line 1110, in get_conflicting_specs
2022-12-06T03:13:43.6194394Z     C = r2.gen_clauses()
2022-12-06T03:13:43.6194868Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/common/io.py", line 86, in decorated
2022-12-06T03:13:43.6195212Z     return f(*args, **kwds)
2022-12-06T03:13:43.6195689Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/resolve.py", line 913, in gen_clauses
2022-12-06T03:13:43.6196037Z     for ms in self.ms_depends(prec):
2022-12-06T03:13:43.6196533Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/resolve.py", line 797, in ms_depends
2022-12-06T03:13:43.6196931Z     deps = [MatchSpec(d) for d in prec.combined_depends]
2022-12-06T03:13:43.6197485Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/models/records.py", line 341, in combined_depends
2022-12-06T03:13:43.6197915Z     result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
2022-12-06T03:13:43.6198448Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 480, in merge
2022-12-06T03:13:43.6198876Z     reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
2022-12-06T03:13:43.6199439Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 480, in <lambda>
2022-12-06T03:13:43.6199868Z     reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
2022-12-06T03:13:43.6200420Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 511, in _merge
2022-12-06T03:13:43.6200800Z     final = this_component.merge(that_component)
2022-12-06T03:13:43.6201415Z   File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 762, in merge
2022-12-06T03:13:43.6201944Z     raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
2022-12-06T03:13:43.6202282Z ValueError: Incompatible component merge:
2022-12-06T03:13:43.6202571Z   - 'mpi_openmpi_*'
2022-12-06T03:13:43.6202854Z   - 'mpi_openmpi_tempest*'
~~~

**Comment by traversaro** [comment]
Possibly related:
* https://gitter.im/conda-forge/conda-forge.github.io?at=5d908e517fe6a605d14e4872
* https://github.com/conda/conda-build/issues/4498
* https://github.com/conda/conda/issues/11442

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/1333 .
