### ISSUE TITLE
Fix conda packages build

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1670]
~~~
  -- Installing: C:/Users/runneradmin/miniconda3/envs/test/conda-bld/robots-configuration_1720485621910/_h_env/Library/share/ICUBcontrib/robots/iCubZagreb01/estimators/wholebodydynamics_standup.xml

Resource usage statistics from building robots-configuration:
   Process count: 6
   CPU time: Sys=0:00:10.7, User=0:00:04.4
   Memory: 127.8M
   Disk usage: 105.9M
   Time elapsed: 0:00:37.7


Packaging robots-configuration
Packaging robots-configuration-2.6.2-had4a028_122
Traceback (most recent call last):
  File "C:\Users\runneradmin\miniconda3\envs\test\Scripts\conda-mambabuild-script.py", line 9, in <module>
number of files: 4753
Fixing permissions
    sys.exit(main())
             ^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\boa\cli\mambabuild.py", line 301, in main
    call_conda_build(action, config)
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\boa\cli\mambabuild.py", line 273, in call_conda_build
    result = api.build(
             ^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\api.py", line 250, in build
    return build_tree(
           ^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 3638, in build_tree
    packages_from_this = build(
                         ^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 2711, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 1865, in bundle_conda
    output["checksums"] = create_info_files(
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 1410, in create_info_files
    files_with_prefix = get_files_with_prefix(m, replacements, files, prefix)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 1049, in get_files_with_prefix
    pfx_matches = have_regex_files(
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 535, in have_regex_files
    match_records_rg = regex_files_rg(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 261, in regex_files_rg
    raise e
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\site-packages\conda_build\build.py", line 253, in regex_files_rg
    subprocess.check_output(args, shell=False).rstrip(b"\n").split(b"\n")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\runneradmin\miniconda3\envs\test\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 206] The filename or extension is too long
Error: Process completed with exit code 1.
~~~

**Comment by traversaro** [comment]
Current failure on Linux (https://github.com/robotology/robotology-superbuild/actions/runs/10361422733/job/28681714233)

~~~
The reported errors are:
- Encountered problems while solving:
-   - package libyarp-3.9.0-h57bc1a5_0 requires libopencv >=4.8.1,<4.8.2.0a0, but none of the providers can be installed
- 

Leaving build/test directories:
  Work:
 /home/runner/miniconda3/envs/test/conda-bld/work 
  Test:
 /home/runner/miniconda3/envs/test/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/runner/miniconda3/envs/test/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /home/runner/miniconda3/envs/test/conda-bld/_build_env 


  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 142, in mamba_get_package_records
    _, link_precs = solver.solve_for_unlink_link_precs(_specs, prefix)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/core/solver.py", line 244, in solve_for_unlink_link_precs
    t = self.solve(specs)
        ^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/core/solver.py", line 234, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - libyarp 3.9.0.*
 - xorg-libxdamage
 - xorg-libxrandr
 - sdl
 - ipopt 3.14.14.*
 - libgcc-ng >=12
 - freeglut
 - icub-firmware-shared
 - libdc1394
 - xorg-libxfixes
 - python 3.10.* *_cpython
 - qt-main 5.15.*
 - gsl 2.7.*
 - libopencv 4.10.0.*
 - ycm-cmake-modules
 - libstdcxx-ng >=12
 - xorg-libxau
 - ace
 - xorg-libxext
 - libxcb 1.15.*
 - libglu
 - xorg-libxxf86vm
 - libode 0.16.2.*

with channels:
 - local
 - conda-forge
 - robotology

The reported errors are:
- Encountered problems while solving:
-   - package libyarp-3.9.0-h57bc1a5_0 requires libopencv >=4.8.1,<4.8.2.0a0, but none of the providers can be installed
- 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/test/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 301, in main
    call_conda_build(action, config)
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 273, in call_conda_build
    result = api.build(
             ^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
           ^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/build.py", line 3638, in build_tree
    packages_from_this = build(
                         ^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/build.py", line 2308, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/render.py", line 916, in expand_outputs
    for output_dict, m in deepcopy(_m).get_output_metadata_set(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/metadata.py", line 2737, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/metadata.py", line 1095, in finalize_outputs_pass
    fm = finalize_metadata(
         ^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/render.py", line 650, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/render.py", line 491, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/render.py", line 444, in _read_upstream_pin_files
    deps, precs, unsat = get_env_dependencies(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/render.py", line 156, in get_env_dependencies
    precs = environ.get_package_records(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 151, in mamba_get_package_records
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("libopencv[version='>=4.8.1,<4.8.2.0a0']"), MatchSpec("libyarp==3.9.0=h57bc1a5_0")}
Error: Process completed with exit code 1.

~~~

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/robotology-superbuild/pull/1695 .
