### ISSUE TITLE
Generation of conda binaries on 2021/05/17 failed

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#744]
~~~
[26/49] Linking CXX executable bin/HumanStateVisualizer
FAILED: bin/HumanStateVisualizer 
: && $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/human-dynamics-estimation-2.2.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib modules/HumanStateVisualizer/CMakeFiles/HumanStateVisualizer.dir/src/main.cpp.o -o bin/HumanStateVisualizer  -Wl,-rpath,:::::::::::::::::::::::  $PREFIX/lib/libYARP_dev.so.3.4.3  $PREFIX/lib/libYARP_init.so.3.4.3  $PREFIX/lib/libidyntree-modelio-urdf.so  $PREFIX/lib/libidyntree-visualization.so  $PREFIX/lib/libYARP_math.so.3.4.3  $PREFIX/lib/libYARP_sig.so.3.4.3  $PREFIX/lib/libYARP_os.so.3.4.3  $PREFIX/lib/libidyntree-sensors.so  $PREFIX/lib/libidyntree-modelio-xml.so  $PREFIX/lib/libidyntree-model.so  $PREFIX/lib/libidyntree-core.so && :
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libGL.so.1, needed by $PREFIX/lib/libIrrlicht.so, not found (try using -rpath or -rpath-link)
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libXxf86vm.so.1, needed by $PREFIX/lib/libIrrlicht.so, not found (try using -rpath or -rpath-link)
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXGetProcAddress'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXMakeCurrent'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeSetViewPort'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeSwitchToMode'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glClearDepth'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glMatrixMode'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeQueryExtension'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glFogi'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glHint'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glVertex3f'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glClearColor'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLineWidth'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexEnvi'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeSetGamma'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXDestroyWindow'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLightfv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glFlush'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGetTexImage'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glVertexPointer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDepthFunc'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDrawElements'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDisableClientState'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glFogfv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLoadIdentity'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glColorMask'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glFrontFace'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLightf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXCreateWindow'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glIsEnabled'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTranslatef'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXQueryVersion'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glMaterialf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPointSize'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGenTextures'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPolygonMode'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glViewport'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glColorPointer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGetString'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexGeni'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDepthMask'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glNormalPointer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPopAttrib'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXGetCurrentDrawable'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glVertex2f'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glMultMatrixf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXGetCurrentDisplay'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPolygonOffset'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexParameterf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glEnable'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glClear'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glMaterialfv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glScissor'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXGetCurrentContext'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glReadPixels'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexCoord2f'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glRectf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glStencilMask'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPushMatrix'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glVertex2i'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDrawBuffer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXSwapBuffers'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glStencilFunc'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGetFloatv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexSubImage2D'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexParameteri'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glStencilOp'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glEnableClientState'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXGetProcAddressARB'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glColor4ub'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glShadeModel'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLightModelfv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGetIntegerv'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexEnvf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXCreateNewContext'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXChooseVisual'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glEnd'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glClipPlane'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glAlphaFunc'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPushAttrib'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDisable'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glCopyTexSubImage2D'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLightModeli'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPixelStorei'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glBegin'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeGetAllModeLines'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glPopMatrix'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXCreateContext'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexCoordPointer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDeleteTextures'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glGetError'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glTexImage2D'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXMakeContextCurrent'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glFogf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glBlendFunc'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glDrawArrays'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXDestroyContext'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glXQueryExtension'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glLoadMatrixf'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glBindTexture'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `XF86VidModeGetGamma'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glCullFace'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glColorMaterial'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libIrrlicht.so: undefined reference to `glReadBuffer'
collect2: error: ld returned 1 exit status
[27/49] Building CXX object wrappers/HumanStateWrapper/CMakeFiles/HumanStateWrapper.dir/HumanStateWrapper.cpp.o
[28/49] Building CXX object devices/HumanStateProvider/CMakeFiles/HumanStateProvider.dir/InverseVelocityKinematics/InverseVelocityKinematics.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/usr/share/miniconda/envs/test/conda-bld/human-dynamics-estimation_1621304377705/work/conda_build.sh']' returned non-zero exit status 1.
~~~

**Comment by traversaro** [comment]
The problem is that any idyntree package can depend transitively on irrlicht and so may need to have the opengl stuff installed, see  https://conda-forge.org/docs/maintainer/knowledge_base.html?#libgl and https://github.com/robotology/robotology-superbuild/blob/545ec06c6915e0581dfaa2a09cc435f37ad5d614/conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake#L128).
