### ISSUE TITLE
2021/07 Conda package generation is failing on Windows

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#822]
~~~
2021-07-13T09:01:57.9307557Z --------------------------------------------------------------------------------------------------------------------
2021-07-13T09:01:57.9308033Z 
2021-07-13T09:01:57.9778389Z BUILD START: ['yarp-telemetry-0.2.0-h3dfdef6_16.tar.bz2']
2021-07-13T09:01:57.9911480Z Traceback (most recent call last):
2021-07-13T09:01:57.9914746Z   File "C:\Miniconda\envs\test\Scripts\conda-mambabuild-script.py", line 10, in <module>
2021-07-13T09:01:57.9915831Z     sys.exit(main())
2021-07-13T09:01:57.9916560Z   File "C:\Miniconda\envs\test\lib\site-packages\boa\cli\mambabuild.py", line 142, in main
2021-07-13T09:01:57.9917373Z     call_conda_build(action, config)
2021-07-13T09:01:57.9918205Z   File "C:\Miniconda\envs\test\lib\site-packages\boa\cli\mambabuild.py", line 120, in call_conda_build
2021-07-13T09:01:57.9918945Z     result = api.build(
2021-07-13T09:01:57.9919633Z   File "C:\Miniconda\envs\test\lib\site-packages\conda_build\api.py", line 186, in build
2021-07-13T09:01:57.9920825Z     return build_tree(
2021-07-13T09:01:57.9921919Z   File "C:\Miniconda\envs\test\lib\site-packages\conda_build\build.py", line 3068, in build_tree
2021-07-13T09:01:57.9922701Z     packages_from_this = build(metadata, stats,
2021-07-13T09:01:57.9923457Z   File "C:\Miniconda\envs\test\lib\site-packages\conda_build\build.py", line 2108, in build
2021-07-13T09:01:57.9924204Z     create_build_envs(top_level_pkg, notest)
2021-07-13T09:01:57.9925000Z   File "C:\Miniconda\envs\test\lib\site-packages\conda_build\build.py", line 1940, in create_build_envs
2021-07-13T09:01:57.9926150Z     environ.create_env(m.config.host_prefix, host_actions, env='host', config=m.config,
2021-07-13T09:01:57.9927166Z   File "C:\Miniconda\envs\test\lib\site-packages\conda_build\environ.py", line 907, in create_env
2021-07-13T09:01:57.9927932Z     display_actions(actions, index)
2021-07-13T09:01:57.9928690Z   File "C:\Miniconda\envs\test\lib\site-packages\conda\exports.py", line 236, in display_actions
2021-07-13T09:01:57.9929490Z     actions['LINK'] = [index[d] for d in actions['LINK']]
2021-07-13T09:01:57.9930273Z   File "C:\Miniconda\envs\test\lib\site-packages\conda\exports.py", line 236, in <listcomp>
2021-07-13T09:01:57.9931203Z     actions['LINK'] = [index[d] for d in actions['LINK']]
2021-07-13T09:01:57.9932545Z KeyError: Dist(channel='file://C:/Miniconda/envs/test/conda-bld', dist_name='matio-cpp-0.1.1-h9963ce3_16', name='matio-cpp', fmt='.tar.bz2', version='0.1.1', build_string='h9963ce3_16', build_number=16, base_url=None, platform=None)
~~~

See for example https://github.com/robotology/robotology-superbuild/actions/runs/1025703228 . No idea what is happening, probably it is worth try to use `conda build` instead of `conda mambabuild` for yarp-telemetry.

**Comment by traversaro** [comment]
Attempted workarounds:
* Switch to mamba v0.14.1: still failing https://github.com/robotology/robotology-superbuild/runs/3060545105?check_suite_focus=true
* Switch to conda build: works, but then the same problem appears on icub-contrib-common: https://github.com/robotology/robotology-superbuild/runs/3060528751?check_suite_focus=true . It seems that this happens for any package that depend on another local package

**Comment by traversaro** [comment]
As `conda build` works fine, I think it is a boa/mamba regression. The last successful build used:
~~~
2021-07-06T00:10:43.7379376Z   anaconda-client                              1.8.0  py38haa95532_0     pkgs/main/win-64       170 KB
2021-07-06T00:10:43.7380096Z   attrs                                       21.2.0  pyhd8ed1ab_0       conda-forge/noarch      44 KB
2021-07-06T00:10:43.7380968Z   backports                                      1.0  py_2               conda-forge/noarch       4 KB
2021-07-06T00:10:43.7381762Z   backports.functools_lru_cache                1.6.4  pyhd8ed1ab_0       conda-forge/noarch       9 KB
2021-07-06T00:10:43.7382833Z   beautifulsoup4                               4.9.3  pyhb0f4dca_0       conda-forge/noarch      86 KB
2021-07-06T00:10:43.7383632Z   boa                                          0.5.0  py38haa244fe_0     conda-forge/win-64     104 KB
2021-07-06T00:10:43.7384331Z   brotlipy                                     0.7.0  py38h294d835_1001  conda-forge/win-64     368 KB
2021-07-06T00:10:43.7385064Z   bzip2                                        1.0.8  h8ffe710_4         conda-forge/win-64     Cached
2021-07-06T00:10:43.7385779Z   cffi                                        1.14.5  py38hd8c33c5_0     conda-forge/win-64     228 KB
2021-07-06T00:10:43.7386491Z   chardet                                      4.0.0  py38haa244fe_1     conda-forge/win-64     224 KB
2021-07-06T00:10:43.7387198Z   clyent                                       1.2.2  py_1               conda-forge/noarch       9 KB
2021-07-06T00:10:43.7387907Z   colorama                                     0.4.4  pyh9f0ad1d_0       conda-forge/noarch      18 KB
2021-07-06T00:10:43.7388781Z   commonmark                                   0.9.1  py_0               conda-forge/noarch      46 KB
2021-07-06T00:10:43.7391104Z   conda                                       4.10.3  py38haa244fe_0     conda-forge/win-64       3 MB
2021-07-06T00:10:43.7391931Z   conda-build                                 3.21.4  py38haa244fe_0     conda-forge/win-64     587 KB
2021-07-06T00:10:43.7392763Z   conda-forge-pinning            2021.07.05.21.22.36  hd8ed1ab_0         conda-forge/noarch      16 KB
2021-07-06T00:10:43.7393725Z   conda-package-handling                       1.7.3  py38h31c79cd_0     conda-forge/win-64     719 KB
2021-07-06T00:10:43.7394641Z   cryptography                                 3.4.7  py38hd7da0ea_0     conda-forge/win-64     706 KB
2021-07-06T00:10:43.7395435Z   dataclasses                                    0.8  pyhc8e2a94_1       conda-forge/noarch       7 KB
2021-07-06T00:10:43.7396214Z   filelock                                    3.0.12  pyh9f0ad1d_0       conda-forge/noarch      10 KB
2021-07-06T00:10:43.7396975Z   future                                      0.18.2  py38haa244fe_3     conda-forge/win-64     736 KB
2021-07-06T00:10:43.7397658Z   glob2                                          0.7  py_0               conda-forge/noarch      11 KB
2021-07-06T00:10:43.7398343Z   idna                                          2.10  pyh9f0ad1d_0       conda-forge/noarch      52 KB
2021-07-06T00:10:43.7399167Z   importlib-metadata                           4.6.1  py38haa244fe_0     conda-forge/win-64      32 KB
2021-07-06T00:10:43.7400017Z   importlib_metadata                           4.6.1  hd8ed1ab_0         conda-forge/noarch       3 KB
2021-07-06T00:10:43.7400824Z   ipython_genutils                             0.2.0  py_1               conda-forge/noarch      21 KB
2021-07-06T00:10:43.7401558Z   jinja2                                       3.0.1  pyhd8ed1ab_0       conda-forge/noarch      99 KB
2021-07-06T00:10:43.7402273Z   joblib                                       1.0.1  pyhd8ed1ab_0       conda-forge/noarch     206 KB
2021-07-06T00:10:43.7402980Z   json5                                        0.9.6  pyhd3eb1b0_0       pkgs/main/noarch        21 KB
2021-07-06T00:10:43.7403686Z   jsonschema                                   3.2.0  py38h32f6830_1     conda-forge/win-64     108 KB
2021-07-06T00:10:43.7404451Z   jupyter_core                                 4.7.1  py38haa244fe_0     conda-forge/win-64      96 KB
2021-07-06T00:10:43.7405191Z   krb5                                        1.19.1  hbae68bd_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7405988Z   libarchive                                   3.5.1  hb45042f_2         conda-forge/win-64     Cached
2021-07-06T00:10:43.7406665Z   libcurl                                     7.77.0  h789b8ee_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7407334Z   libiconv                                      1.16  he774522_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7407976Z   liblief                                     0.11.5  h0e60522_0         conda-forge/win-64       5 MB
2021-07-06T00:10:43.7409040Z   libsolv                                     0.7.19  h7755175_2         conda-forge/win-64     Cached
2021-07-06T00:10:43.7409989Z   libssh2                                      1.9.0  h680486a_6         conda-forge/win-64     Cached
2021-07-06T00:10:43.7410992Z   libxml2                                     2.9.12  hf5bbc77_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7411839Z   lz4-c                                        1.9.3  h8ffe710_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7412642Z   lzo                                           2.10  he774522_1000      conda-forge/win-64     Cached
2021-07-06T00:10:43.7413475Z   m2-msys2-runtime               2.5.0.17080.65c939c  3                  conda-forge/win-64       3 MB
2021-07-06T00:10:43.7414292Z   m2-patch                                     2.7.5  2                  conda-forge/win-64      90 KB
2021-07-06T00:10:43.7415286Z   m2w64-gcc-libgfortran                        5.3.0  6                  conda-forge/win-64     342 KB
2021-07-06T00:10:43.7416649Z   m2w64-gcc-libs                               5.3.0  7                  conda-forge/win-64     520 KB
2021-07-06T00:10:43.7417538Z   m2w64-gcc-libs-core                          5.3.0  7                  conda-forge/win-64     214 KB
2021-07-06T00:10:43.7418379Z   m2w64-gmp                                    6.1.0  2                  conda-forge/win-64     726 KB
2021-07-06T00:10:43.7419263Z   m2w64-libwinpthread-git         5.0.0.4634.697f757  2                  conda-forge/win-64      31 KB
2021-07-06T00:10:43.7420223Z   mamba                                       0.14.1  py38hdd88130_0     conda-forge/win-64     Cached
2021-07-06T00:10:43.7421116Z   markupsafe                                   2.0.1  py38h294d835_0     conda-forge/win-64      25 KB
2021-07-06T00:10:43.7422074Z   menuinst                                    1.4.16  py38h32f6830_1     conda-forge/win-64      95 KB
2021-07-06T00:10:43.7422917Z   msys2-conda-epoch                         20160418  1                  conda-forge/win-64       3 KB
2021-07-06T00:10:43.7423765Z   multisheller                                 0.2.0  pyhd8ed1ab_0       conda-forge/noarch      16 KB
2021-07-06T00:10:43.7424605Z   nbformat                                     5.1.3  pyhd8ed1ab_0       conda-forge/noarch      47 KB
2021-07-06T00:10:43.7425367Z   ninja                                       1.10.2  h5362a0b_0         conda-forge/win-64     273 KB
2021-07-06T00:10:43.7426132Z   pkginfo                                      1.7.0  pyhd8ed1ab_0       conda-forge/noarch      22 KB
2021-07-06T00:10:43.7426974Z   prompt-toolkit                              3.0.19  pyha770c72_0       conda-forge/noarch     244 KB
2021-07-06T00:10:43.7427820Z   prompt_toolkit                              3.0.19  hd8ed1ab_0         conda-forge/noarch       4 KB
2021-07-06T00:10:43.7428853Z   psutil                                       5.8.0  py38h294d835_1     conda-forge/win-64     364 KB
2021-07-06T00:10:43.7429694Z   py-lief                                     0.11.5  py38h885f38d_0     conda-forge/win-64       2 MB
2021-07-06T00:10:43.7430559Z   pycosat                                      0.6.3  py38h294d835_1006  conda-forge/win-64     102 KB
2021-07-06T00:10:43.7431431Z   pycparser                                     2.20  pyh9f0ad1d_2       conda-forge/noarch      94 KB
2021-07-06T00:10:43.7432303Z   pygments                                     2.9.0  pyhd8ed1ab_0       conda-forge/noarch     754 KB
2021-07-06T00:10:43.7433197Z   pyopenssl                                   20.0.1  pyhd8ed1ab_0       conda-forge/noarch      48 KB
2021-07-06T00:10:43.7434075Z   pyrsistent                                  0.17.3  py38h294d835_2     conda-forge/win-64      92 KB
2021-07-06T00:10:43.7434918Z   pysocks                                      1.7.1  py38haa244fe_3     conda-forge/win-64      28 KB
2021-07-06T00:10:43.7435838Z   python-dateutil                              2.8.1  py_0               conda-forge/noarch     220 KB
2021-07-06T00:10:43.7436829Z   python-libarchive-c                            3.1  py38haa244fe_0     conda-forge/win-64      29 KB
2021-07-06T00:10:43.7437784Z   pytz                                        2021.1  pyhd8ed1ab_0       conda-forge/noarch     239 KB
2021-07-06T00:10:43.7438617Z   pywin32                                        300  py38h294d835_0     conda-forge/win-64       7 MB
2021-07-06T00:10:43.7439420Z   pyyaml                                       5.4.1  py38h294d835_0     conda-forge/win-64     159 KB
2021-07-06T00:10:43.7440349Z   reproc                                      14.2.1  h8ffe710_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7441151Z   reproc-cpp                                  14.2.1  h0e60522_0         conda-forge/win-64     Cached
2021-07-06T00:10:43.7441945Z   requests                                    2.25.1  pyhd3deb0d_0       conda-forge/noarch      51 KB
2021-07-06T00:10:43.7443228Z   rich                                        10.5.0  py38haa244fe_0     conda-forge/win-64     341 KB
2021-07-06T00:10:43.7443996Z   ripgrep                                     13.0.0  h7f3b576_0         conda-forge/win-64       2 MB
2021-07-06T00:10:43.7444832Z   ruamel.yaml                                0.17.10  py38h294d835_0     conda-forge/win-64     170 KB
2021-07-06T00:10:43.7445690Z   ruamel.yaml.clib                             0.2.2  py38h294d835_2     conda-forge/win-64     128 KB
2021-07-06T00:10:43.7446515Z   ruamel_yaml                               0.15.100  py38h2bbff1b_0     pkgs/main/win-64       273 KB
2021-07-06T00:10:43.7447276Z   six                                         1.16.0  pyh6c4a22f_0       conda-forge/noarch      14 KB
2021-07-06T00:10:43.7448578Z   soupsieve                                    2.2.1  pyhd3eb1b0_0       pkgs/main/noarch        32 KB
2021-07-06T00:10:43.7449644Z   tk                                          8.6.10  h8ffe710_1         conda-forge/win-64     Cached
2021-07-06T00:10:43.7452396Z   tqdm                                        4.61.1  pyhd8ed1ab_0       conda-forge/noarch      79 KB
2021-07-06T00:10:43.7453494Z   traitlets                                    5.0.5  py_0               conda-forge/noarch      81 KB
2021-07-06T00:10:43.7461974Z   typing_extensions                         3.10.0.0  pyha770c72_0       conda-forge/noarch      28 KB
2021-07-06T00:10:43.7463907Z   urllib3                                     1.26.6  pyhd8ed1ab_0       conda-forge/noarch      99 KB
2021-07-06T00:10:43.7465395Z   wcwidth                                      0.2.5  pyh9f0ad1d_2       conda-forge/noarch      33 KB
2021-07-06T00:10:43.7471413Z   win_inet_pton                                1.1.0  py38haa244fe_2     conda-forge/win-64       8 KB
2021-07-06T00:10:43.7482234Z   xz                                           5.2.5  h62dcd97_1         conda-forge/win-64     Cached
2021-07-06T00:10:43.7483231Z   yaml                                         0.2.5  he774522_0         conda-forge/win-64      61 KB
2021-07-06T00:10:43.7488672Z   zipp                                         3.5.0  pyhd8ed1ab_0       conda-forge/noarch      12 KB
2021-07-06T00:10:43.7489530Z   zlib                                        1.2.11  h62dcd97_1010      conda-forge/win-64     126 KB
2021-07-06T00:10:43.7490476Z   zstd                                         1.5.0  h6255e5f_0         conda-forge/win-64     Cached
~~~
while the broken ones:
~~~
2021-07-13T20:07:19.3834178Z   anaconda-client                              1.8.0  py38haa95532_0     pkgs/main/win-64       170 KB
2021-07-13T20:07:19.3834839Z   attrs                                       21.2.0  pyhd8ed1ab_0       conda-forge/noarch      44 KB
2021-07-13T20:07:19.3835426Z   backports                                      1.0  py_2               conda-forge/noarch       4 KB
2021-07-13T20:07:19.3836138Z   backports.functools_lru_cache                1.6.4  pyhd8ed1ab_0       conda-forge/noarch       9 KB
2021-07-13T20:07:19.3837153Z   beautifulsoup4                               4.9.3  pyhb0f4dca_0       conda-forge/noarch      86 KB
2021-07-13T20:07:19.3837786Z   boa                                          0.6.0  py38haa244fe_0     conda-forge/win-64     105 KB
2021-07-13T20:07:19.3838385Z   brotlipy                                     0.7.0  py38h294d835_1001  conda-forge/win-64     368 KB
2021-07-13T20:07:19.3838972Z   bzip2                                        1.0.8  h8ffe710_4         conda-forge/win-64     Cached
2021-07-13T20:07:19.3839569Z   cffi                                        1.14.6  py38hd8c33c5_0     conda-forge/win-64     228 KB
2021-07-13T20:07:19.3840179Z   chardet                                      4.0.0  py38haa244fe_1     conda-forge/win-64     224 KB
2021-07-13T20:07:19.3840754Z   clyent                                       1.2.2  py_1               conda-forge/noarch       9 KB
2021-07-13T20:07:19.3842879Z   colorama                                     0.4.4  pyh9f0ad1d_0       conda-forge/noarch      18 KB
2021-07-13T20:07:19.3843565Z   commonmark                                   0.9.1  py_0               conda-forge/noarch      46 KB
2021-07-13T20:07:19.3844144Z   conda                                       4.10.3  py38haa244fe_0     conda-forge/win-64       3 MB
2021-07-13T20:07:19.3844780Z   conda-build                                 3.21.4  py38haa244fe_0     conda-forge/win-64     587 KB
2021-07-13T20:07:19.3845489Z   conda-forge-pinning            2021.07.11.12.10.29  hd8ed1ab_0         conda-forge/noarch      16 KB
2021-07-13T20:07:19.3846272Z   conda-package-handling                       1.7.3  py38h31c79cd_0     conda-forge/win-64     719 KB
2021-07-13T20:07:19.3847119Z   cryptography                                 3.4.7  py38hd7da0ea_0     conda-forge/win-64     706 KB
2021-07-13T20:07:19.3847797Z   dataclasses                                    0.8  pyhc8e2a94_1       conda-forge/noarch       7 KB
2021-07-13T20:07:19.3848448Z   filelock                                    3.0.12  pyh9f0ad1d_0       conda-forge/noarch      10 KB
2021-07-13T20:07:19.3849077Z   future                                      0.18.2  py38haa244fe_3     conda-forge/win-64     736 KB
2021-07-13T20:07:19.3849651Z   glob2                                          0.7  py_0               conda-forge/noarch      11 KB
2021-07-13T20:07:19.3850209Z   idna                                          2.10  pyh9f0ad1d_0       conda-forge/noarch      52 KB
2021-07-13T20:07:19.3850878Z   importlib-metadata                           4.6.1  py38haa244fe_0     conda-forge/win-64      32 KB
2021-07-13T20:07:19.3851597Z   importlib_metadata                           4.6.1  hd8ed1ab_0         conda-forge/noarch       3 KB
2021-07-13T20:07:19.3852237Z   ipython_genutils                             0.2.0  py_1               conda-forge/noarch      21 KB
2021-07-13T20:07:19.3852859Z   jinja2                                       3.0.1  pyhd8ed1ab_0       conda-forge/noarch      99 KB
2021-07-13T20:07:19.3853478Z   joblib                                       1.0.1  pyhd8ed1ab_0       conda-forge/noarch     206 KB
2021-07-13T20:07:19.3854053Z   json5                                        0.9.6  pyhd3eb1b0_0       pkgs/main/noarch        21 KB
2021-07-13T20:07:19.3854657Z   jsonschema                                   3.2.0  py38h32f6830_1     conda-forge/win-64     108 KB
2021-07-13T20:07:19.3855287Z   jupyter_core                                 4.7.1  py38haa244fe_0     conda-forge/win-64      96 KB
2021-07-13T20:07:19.3855909Z   krb5                                        1.19.1  hbae68bd_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3856517Z   libarchive                                   3.5.1  hb45042f_2         conda-forge/win-64     Cached
2021-07-13T20:07:19.3857176Z   libcurl                                     7.77.0  h789b8ee_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3857897Z   libiconv                                      1.16  he774522_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3858483Z   liblief                                     0.11.5  h0e60522_0         conda-forge/win-64       5 MB
2021-07-13T20:07:19.3859043Z   libsolv                                     0.7.19  h7755175_5         conda-forge/win-64     Cached
2021-07-13T20:07:19.3859629Z   libssh2                                      1.9.0  h680486a_6         conda-forge/win-64     Cached
2021-07-13T20:07:19.3860238Z   libxml2                                     2.9.12  hf5bbc77_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3860834Z   lz4-c                                        1.9.3  h8ffe710_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3861421Z   lzo                                           2.10  he774522_1000      conda-forge/win-64     Cached
2021-07-13T20:07:19.3862020Z   m2-msys2-runtime               2.5.0.17080.65c939c  3                  conda-forge/win-64       3 MB
2021-07-13T20:07:19.3863008Z   m2-patch                                     2.7.5  2                  conda-forge/win-64      90 KB
2021-07-13T20:07:19.3863657Z   m2w64-gcc-libgfortran                        5.3.0  6                  conda-forge/win-64     342 KB
2021-07-13T20:07:19.3864308Z   m2w64-gcc-libs                               5.3.0  7                  conda-forge/win-64     520 KB
2021-07-13T20:07:19.3864916Z   m2w64-gcc-libs-core                          5.3.0  7                  conda-forge/win-64     214 KB
2021-07-13T20:07:19.3865517Z   m2w64-gmp                                    6.1.0  2                  conda-forge/win-64     726 KB
2021-07-13T20:07:19.3866168Z   m2w64-libwinpthread-git         5.0.0.4634.697f757  2                  conda-forge/win-64      31 KB
2021-07-13T20:07:19.3866882Z   mamba                                       0.15.0  py38hdd88130_0     conda-forge/win-64     656 KB
2021-07-13T20:07:19.3867501Z   markupsafe                                   2.0.1  py38h294d835_0     conda-forge/win-64      25 KB
2021-07-13T20:07:19.3868128Z   menuinst                                    1.4.16  py38h32f6830_1     conda-forge/win-64      95 KB
2021-07-13T20:07:19.3868771Z   msys2-conda-epoch                         20160418  1                  conda-forge/win-64       3 KB
2021-07-13T20:07:19.3869423Z   nbformat                                     5.1.3  pyhd8ed1ab_0       conda-forge/noarch      47 KB
2021-07-13T20:07:19.3869997Z   ninja                                       1.10.2  h5362a0b_0         conda-forge/win-64     273 KB
2021-07-13T20:07:19.3870573Z   pkginfo                                      1.7.1  pyhd8ed1ab_0       conda-forge/noarch      22 KB
2021-07-13T20:07:19.3871228Z   prompt-toolkit                              3.0.19  pyha770c72_0       conda-forge/noarch     244 KB
2021-07-13T20:07:19.3871873Z   prompt_toolkit                              3.0.19  hd8ed1ab_0         conda-forge/noarch       4 KB
2021-07-13T20:07:19.3872478Z   psutil                                       5.8.0  py38h294d835_1     conda-forge/win-64     364 KB
2021-07-13T20:07:19.3873069Z   py-lief                                     0.11.5  py38h885f38d_0     conda-forge/win-64       2 MB
2021-07-13T20:07:19.3873652Z   pycosat                                      0.6.3  py38h294d835_1006  conda-forge/win-64     102 KB
2021-07-13T20:07:19.3874277Z   pycparser                                     2.20  pyh9f0ad1d_2       conda-forge/noarch      94 KB
2021-07-13T20:07:19.3874901Z   pygments                                     2.9.0  pyhd8ed1ab_0       conda-forge/noarch     754 KB
2021-07-13T20:07:19.3875529Z   pyopenssl                                   20.0.1  pyhd8ed1ab_0       conda-forge/noarch      48 KB
2021-07-13T20:07:19.3876160Z   pyrsistent                                  0.17.3  py38h294d835_2     conda-forge/win-64      92 KB
2021-07-13T20:07:19.3876818Z   pysocks                                      1.7.1  py38haa244fe_3     conda-forge/win-64      28 KB
2021-07-13T20:07:19.3877519Z   python-dateutil                              2.8.1  py_0               conda-forge/noarch     220 KB
2021-07-13T20:07:19.3878241Z   python-libarchive-c                            3.1  py38haa244fe_0     conda-forge/win-64      29 KB
2021-07-13T20:07:19.3878934Z   pytz                                        2021.1  pyhd8ed1ab_0       conda-forge/noarch     239 KB
2021-07-13T20:07:19.3879516Z   pywin32                                        300  py38h294d835_0     conda-forge/win-64       7 MB
2021-07-13T20:07:19.3880114Z   pyyaml                                       5.4.1  py38h294d835_0     conda-forge/win-64     159 KB
2021-07-13T20:07:19.3880704Z   reproc                                      14.2.1  h8ffe710_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3881310Z   reproc-cpp                                  14.2.1  h0e60522_0         conda-forge/win-64     Cached
2021-07-13T20:07:19.3881941Z   requests                                    2.25.1  pyhd3deb0d_0       conda-forge/noarch      51 KB
2021-07-13T20:07:19.3883401Z   rich                                        10.6.0  py38haa244fe_0     conda-forge/win-64     341 KB
2021-07-13T20:07:19.3884152Z   ripgrep                                     13.0.0  h7f3b576_0         conda-forge/win-64       2 MB
2021-07-13T20:07:19.3884867Z   ruamel.yaml                                0.17.10  py38h294d835_0     conda-forge/win-64     170 KB
2021-07-13T20:07:19.3885621Z   ruamel.yaml.clib                             0.2.2  py38h294d835_2     conda-forge/win-64     128 KB
2021-07-13T20:07:19.3886364Z   ruamel_yaml                               0.15.100  py38h2bbff1b_0     pkgs/main/win-64       273 KB
2021-07-13T20:07:19.3887468Z   six                                         1.16.0  pyh6c4a22f_0       conda-forge/noarch      14 KB
2021-07-13T20:07:19.3888239Z   soupsieve                                    2.2.1  pyhd3eb1b0_0       pkgs/main/noarch        32 KB
2021-07-13T20:07:19.3888854Z   tk                                          8.6.10  h8ffe710_1         conda-forge/win-64     Cached
2021-07-13T20:07:19.3889452Z   tqdm                                        4.61.2  pyhd8ed1ab_1       conda-forge/noarch      80 KB
2021-07-13T20:07:19.3890018Z   traitlets                                    5.0.5  py_0               conda-forge/noarch      81 KB
2021-07-13T20:07:19.3890647Z   typing_extensions                         3.10.0.0  pyha770c72_0       conda-forge/noarch      28 KB
2021-07-13T20:07:19.3891285Z   urllib3                                     1.26.6  pyhd8ed1ab_0       conda-forge/noarch      99 KB
2021-07-13T20:07:19.3892431Z   wcwidth                                      0.2.5  pyh9f0ad1d_2       conda-forge/noarch      33 KB
2021-07-13T20:07:19.3893175Z   win_inet_pton                                1.1.0  py38haa244fe_2     conda-forge/win-64       8 KB
2021-07-13T20:07:19.3893873Z   xz                                           5.2.5  h62dcd97_1         conda-forge/win-64     Cached
2021-07-13T20:07:19.3894524Z   yaml                                         0.2.5  he774522_0         conda-forge/win-64      61 KB
2021-07-13T20:07:19.3895462Z   zipp                                         3.5.0  pyhd8ed1ab_0       conda-forge/noarch      12 KB
2021-07-13T20:07:19.3896212Z   zlib                                        1.2.11  h62dcd97_1010      conda-forge/win-64     126 KB
2021-07-13T20:07:19.3896844Z   zstd                                         1.5.0  h6255e5f_0         conda-forge/win-64     Cached
~~~

So it could be a boa regression from 0.5.0 to 0.6.0 .

**Comment by traversaro** [comment]
Pinning boa to 0.5.0 or mamba to 0.14.1 still creates problem, and unfortunatly we do not have the exact environment corresponding to the past successful build (this will be fixed in https://github.com/robotology/robotology-superbuild/pull/824).

**Comment by traversaro** [comment]
A possibly related upstream bug is https://github.com/mamba-org/boa/issues/165 .
